apiVersion: v1
kind: ConfigMap
metadata:
  name: drupal-config
  namespace: subtel
data:
  DRUPAL_ENV: "production"
  DRUPAL_HOST: "localhost"
  DRUPAL_LANGCODE: "es"
  DRUPAL_THEME: "subtel_improved"
