apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: subtel
type: Opaque
stringData:
  DB_NAME: drupal
  DB_USER: admin@subtel.gob.cl
  DB_PASSWORD: changeme
  DB_HOST: postgres
  DB_PORT: "5432"
